from decimal import Decimal

BTC_PRICE = Decimal("91000")

PRIME_LICENCE_COST = Decimal("1200") / BTC_PRICE
PLATINUM_LICENCE_COST = Decimal("1000") / BTC_PRICE
PRIME_MAX_NUM_CARDS = 50
PLATINUM_MAX_NUM_CARDS = 30

CARD_COST: Decimal = Decimal("0.0041")
CARD_MINES_BTC_PER_DAY = Decimal("0.00003947")
CARD_EXPENSES_PER_DAY = CARD_MINES_BTC_PER_DAY * Decimal("0.3")
CARD_PROFIT_THRESHOLD = Decimal("14")
