from decimal import Decimal, ROUND_CEILING

BTC_PRICE = Decimal("91000")

# licence
PRIME_LICENCE_COST = Decimal("1200") / BTC_PRICE
PLATINUM_LICENCE_COST = Decimal("1000") / BTC_PRICE
PRIME_MAX_NUM_CARDS = 50
PLATINUM_MAX_NUM_CARDS = 30

# card
CARD_COST: Decimal = Decimal("0.0041")
CARD_MINES_BTC_PER_DAY = Decimal("0.00003947")
CARD_EXPENSES_PER_DAY = CARD_MINES_BTC_PER_DAY * Decimal("0.3")
CARD_PROFIT_THRESHOLD = Decimal("14")
CARD_NUM_MINING_DAYS = (CARD_COST / CARD_MINES_BTC_PER_DAY).to_integral_value(rounding=ROUND_CEILING)